config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  get 'tasks/show_mine', to: 'tasks#show_mine'
  get 'tasks/asign', to: 'tasks#asign'

  get 'tasks', to: 'tasks#index'
  delete 'tasks/:id', to: 'tasks#destroy'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  STATUS = ["未対応","対応中","完了"]

  validates :title,  presence: true
  validates :deadline,  presence: true
  validates :status,  presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :confirmable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :asign, :update, :destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.where.not(status: 2).order(deadline: "ASC")
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  def show_mine
    @user = User.find(current_user.id)
    @tasks = @user.tasks.where.not(status: 2).order(deadline: "ASC")
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def asign
    @users = User.all
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "タスクを作成しました！" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @task.user_id = params[:user_id]
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "タスクを更新しました！" }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "タスクは削除されました！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :status, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="logo">
      <%= link_to 'タスク管理アプリ', root_path, class: "link_to" %>
  </div>

  <div id="hamburger">
      <div class="icon">
          <span></span>
          <span></span>
          <span></span>
      </div>
  </div>

  <nav class="sm">
    <ul>
      <li class="link_to">
        <%= link_to 'マイタスク', tasks_show_mine_path %>
      </li>
      <li class="link_to">
        <%= link_to 'タスク一覧', root_path %>
      </li>
      <li class="link_to">
        <%= link_to 'ユーザ設定', edit_user_registration_path %>
      </li>
      <li class="link_to">
        <% if current_user %>
          <%= button_to 'サインアウト', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= button_to 'サインイン', new_user_session_path %>
        <% end %>
      </li>
    </ul>
  </nav>

  <nav class="pc">
    <ul>
        <li>
          <%= link_to 'マイタスク', tasks_show_mine_path ,class: "link_to" %>
        </li>
        <li>
          <%= link_to 'タスク一覧', root_path ,class: "link_to" %>
        </li>
        <li>
          <%= link_to 'ユーザ設定', edit_user_registration_path ,class: "link_to" %>
        </li>
        <li style="justify-content: center; display: flex; align-items: center;">
          <% if current_user %>
            <%= button_to 'サインアウト', destroy_user_session_path, method: :delete, class: "button_to" %>
          <% else %>
            <%= button_to 'サインイン', new_user_session_path ,class: "button_to" %>
          <% end %>
        </li>
      </ul>
  </nav>

  <% if current_user %>
    <p id="header-message" style="margin: 0 0 0 auto;">ようこそ<%= current_user.name%>さん</p>
  <% end %>
</header>

<script>
  $('#hamburger').on('click', function(){
    $('.icon').toggleClass('close');
    $('.sm').slideToggle();
  });
</script>

app/views/layouts/_task-list.html.erb
<div class="row ItemList">
  <% @tasks.each do |task| %>
    <% if task.user_id == current_user.id %>
      <div class="col-md-6" id="cell" >
    <% else %>
      <div class="col-md-6" >
    <% end %>
        <div style="margin: 10px; border: 1px solid #000">
        <% if task.user_id == current_user.id %>
          <div class="card-header" style="background-color: rgb(247, 185, 183);">
        <% else %>
          <div class="card-header" style="background-color: rgb(169, 224, 169);">
        <% end %>
          <% if DateTime.current > task[:deadline] %>
            <% if task.user_id == current_user.id %>
              <h2 class="text-danger">
            <% else %>
              <h2 class="text-success">
            <% end %>
            <span class="spinner-grow text-danger"></span><%= task.title %><h2>
          <% else %>
            <% if task.user_id == current_user.id %>
              <h2 class="text-danger">
            <% else %>
              <h2 class="text-success">
            <% end %>
            <%= task.title %><h2>
          <% end %>
          </div>
          <div class="card-body">
            <p><%= task.content%><p>
            <p>期限：<%= task.deadline.strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
            <p>担当者：<%= task.user.name %><p>
            <p>ステータス：<%= Task::STATUS[task.status] %></p>

            <div class="form-group">
              <%= link_to '詳細', task_path(task), class: 'btn btn-secondary text-white' %>
              <% if task.user_id == current_user.id %>
                <%= link_to '編集', edit_task_path(task), class: 'btn btn-primary text-white' %>
                <%= button_to '削除', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger text-white'%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achieve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container " style="margin: 0 auto;">
      <p id="notice" class="text-success"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if @task.errors.any? %>
    <div>
      <ul style="color: red">
        <% @task.errors.full_messages.each do |message| %>
          <li>・<%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title, class: "form-control"  %>
  </div>

  <div class="field mb-3">
    <%= form.label :content, "内容" %>
    <%= form.text_area :content, class: "form-control"  %>
  </div>

  <%= hidden_field_tag :user_id, current_user.id %>

  <div class="field mb-3">
    <%= form.label :deadline, "期限" %>
    <br>
    <%= form.datetime_select :deadline, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :status, "ステータス" %>
    <%= form.radio_button :status, 0 %>
    <%= form.label "未対応" %>
    <%= form.radio_button :status, 1 %>
    <%= form.label "対応中" %>
    <% if params[:action] == "edit" %>
      <%= form.radio_button :status, 2 %>
      <%= form.label "完了" %>
    <% end %>
  </div>

  <div class="actions float-right" style="display: inline-block;">
    <% if params[:action] == "new" %>
      <%= form.submit "登録する", class: 'btn btn-success text-white' %>
    <% else %>
      <%= form.submit "更新する", class: 'btn btn-success text-white' %>
    <% end %>
  </div>
<% end %>

app/views/tasks/asign.html.erb
<h1>アサイン</h1>

<div class="" style="display: inline-block;">
  <p style="font-weight: bold;">現在アサインされているユーザー</p>
  <p><%= @task.user.name %></p>
</div>

<%= form_with(model: @task, local: true) do |f| %>
  <div class="" style="display: inline-block;">
    <div class="form-group">
      <%= f.label :user_id, "新しくアサインするユーザー" %>
      <%= f.select :user_id, User.all.map{|u| [u.name, u.id]}, {}, {class: 'form-select form-select-lg mb-3'} %>
    </div>
  </div>

  <%= hidden_field_tag :id, @task.id %>

  <div class="form-group">
    <%= f.submit 'アサインする', class: 'btn btn-success btn-block mb-3' %>
  </div>
<% end %>

<div class="row g-0">
  <div class="col-md-12 bg-light">
    <div class="card-body">
      <h2 class="card-name"><%= @task.title %></h2>
      <p class="card-text"><%= @task.content %></p>
      <p class="card-text">期日：<%= @task.deadline.strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
      <p class="card-text">ステータス：<%= Task::STATUS[@task.status] %></p>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task %>

<br>
<%= link_to '戻る', :back, class: "btn btn-secondary text-white" %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%= render 'layouts/task-list' %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<div class="row g-0">
  <div class="col-md-12 bg-light">
    <div class="card-body">
      <h2><%= @task.title %></h2>
      <p><%= @task.content %></p>
      <p>期限：<%= @task.deadline.strftime("%Y年%-m月%-d日 %-H時%-M分") %></p>
      <p>担当者：<%= @task.user.name %></p>
      <p>ステータス：<%= Task::STATUS[@task.status]%></p>
      <div>
        <% if @task.user_id == current_user.id %>
          <%= link_to '編集', edit_task_path(@task), class: 'btn btn-primary text-white' %>
          <%= link_to 'アサイン', tasks_asign_path(id: @task.id), class: 'btn btn-success text-white' %>
          <%= button_to '削除', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'd-inline btn btn-danger text-white' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show_mine.html.erb
<h1>マイタスク一覧</h1>

<div id="new-blog-link" class="button">
  <%= link_to '新規作成', new_task_path, class: 'btn btn-outline-secondary' %>
</div>

<%= render 'layouts/task-list' %>